### ISSUE TITLE
Issue with NEO

### ISSUE THREAD

**Issue by jesuismaxime** [naboo/craft-siteduplicate#1]
Unable to duplicate content site to site. At first I got some error regarding SEO plugin (by ethercreative). After deactivate it and delete my field from my section; I got an error of ID conflict (figure out that the entry cant already exists in the destination site). So I delete my second site, recreate it, deactivate the 'propagation' entry settings and retry a Duplicate and got that error regarding Neo :

```
yii\base\Exception: There was a problem getting the parent element. in /Users/[...]/Sites/soproq.local/vendor/craftcms/cms/src/services/Structures.php:238
Stack trace:
#0 /Users/[...]/Sites/soproq.local/vendor/spicyweb/craft-neo/src/services/Blocks.php(357): craft\services\Structures->append(544, Object(benf\neo\elements\Block), Object(benf\neo\elements\Block))
#1 /Users/[...]/Sites/soproq.local/vendor/spicyweb/craft-neo/src/services/Fields.php(342): benf\neo\services\Blocks->buildStructure(Array, Object(benf\neo\models\BlockStructure))
#2 /Users/[...]/Sites/soproq.local/vendor/spicyweb/craft-neo/src/Field.php(589): benf\neo\services\Fields->saveValue(Object(benf\neo\Field), Object(craft\elements\Entry), true)
```

I need to duplicate the entire section from French to the English site so the client will only need to edit the content - and will dont need to recreate all the Neo/Matrix structure of the pages.

✌️ 

EDIT: Just notice that all my attempts almost worked, I got like 5-6 duplicatas of the same page (the one I was trying to duplicate) on my French site.

**Comment by naboo** [comment]
So there different things in here. Let me try and help.

First: If the entry can't be duplicated the duplicate will end up in the source Site. That's why you have duplicates in your French site of the entry you tried to duplicate.

Second: There shouldn't be any ID conflicts since the Plugin always creates new entries, so the same entry can in theory be duplicated over and over again with no issue.

Third: I wonder if the error you are getting is that something within your Neo field have a reference to some other element within the French site(?). Since Site Duplicate creates a new entry with what's on the actual entry page the only issues you could run into should be reference issues.

Could you provide some more info on the Neo field and how it looks / is set up in Craft?

**Comment by jesuismaxime** [comment]
Just to be sure and avoid searching down a solution; Your plugin cant duplicate the content of an entry in the same entry (ie ID 9/fr to ID 9/en ?)

**Comment by naboo** [comment]
No, this Plugin duplicates an entry into a new entry. If you want to copy entry data within a entry that already exists there's a Plugin called site-copy which let's you do this.

Site Duplicate let's you duplicate an entry in Site A to Site B as a new entry.
